stages:
  - build
  - publish
build:
  stage: build
  image: node:6
  only:
    - tags
    - "/^v\\d{1,2}\\.\\d{1,2}\\.\\d{1,2}$/"
  artifacts:
    paths:
      - dist/
    expire_in: 30 minutes
  before_script:
    - npm install -g gulp-cli
    - npm install
  script: gulp zip
publish:
  image: inetprocess/gitlab-release
  stage: publish
  only:
    - tags
    - "/^v\\d{1,2}\\.\\d{1,2}\\.\\d{1,2}$/"
  dependencies:
    - build
  script:
    - gitlab-release --message 'Release message' dist/blank-*.zip
